import { UserDto } from './user-dto'

export const getTestData = (): UserDto[] => [
  { lastName: 'lastName1', firstName: 'firstName1', secondName: 'secondName1' } as UserDto,
  { lastName: 'lastName2', firstName: 'firstName2', secondName: 'secondName2' } as UserDto,
  { lastName: 'lastName3', firstName: 'firstName3', secondName: 'secondName3' } as UserDto,
  { lastName: 'lastName4', firstName: 'firstName4', secondName: 'secondName4' } as UserDto,
  { lastName: 'lastName5', firstName: 'firstName5', secondName: 'secondName5' } as UserDto,
  { lastName: 'lastName6', firstName: 'firstName6', secondName: 'secondName6' } as UserDto,
  { lastName: 'lastName7', firstName: 'firstName7', secondName: 'secondName7' } as UserDto,
  { lastName: 'lastName8', firstName: 'firstName8', secondName: 'secondName8' } as UserDto,
  { lastName: 'lastName9', firstName: 'firstName9', secondName: 'secondName9' } as UserDto,
  { lastName: 'lastName10', firstName: 'firstName10', secondName: 'secondName10' } as UserDto,
  { lastName: 'lastName11', firstName: 'firstName11', secondName: 'secondName11' } as UserDto,
  { lastName: 'lastName12', firstName: 'firstName12', secondName: 'secondName12' } as UserDto,
  { lastName: 'lastName13', firstName: 'firstName13', secondName: 'secondName13' } as UserDto,
  { lastName: 'lastName14', firstName: 'firstName14', secondName: 'secondName14' } as UserDto,
  { lastName: 'lastName15', firstName: 'firstName15', secondName: 'secondName15' } as UserDto,
  { lastName: 'lastName16', firstName: 'firstName16', secondName: 'secondName16' } as UserDto,
  { lastName: 'lastName17', firstName: 'firstName17', secondName: 'secondName17' } as UserDto,
  { lastName: 'lastName18', firstName: 'firstName18', secondName: 'secondName18' } as UserDto,
  { lastName: 'lastName19', firstName: 'firstName19', secondName: 'secondName19' } as UserDto,
  { lastName: 'lastName20', firstName: 'firstName20', secondName: 'secondName20' } as UserDto,
  { lastName: 'lastName21', firstName: 'firstName21', secondName: 'secondName21' } as UserDto,
  { lastName: 'lastName22', firstName: 'firstName22', secondName: 'secondName22' } as UserDto,
  { lastName: 'lastName23', firstName: 'firstName23', secondName: 'secondName23' } as UserDto,
  { lastName: 'lastName24', firstName: 'firstName24', secondName: 'secondName24' } as UserDto,
  { lastName: 'lastName25', firstName: 'firstName25', secondName: 'secondName25' } as UserDto,
  { lastName: 'lastName26', firstName: 'firstName26', secondName: 'secondName26' } as UserDto,
  { lastName: 'lastName27', firstName: 'firstName27', secondName: 'secondName27' } as UserDto,
  { lastName: 'lastName28', firstName: 'firstName28', secondName: 'secondName28' } as UserDto,
  { lastName: 'lastName29', firstName: 'firstName29', secondName: 'secondName29' } as UserDto,
  { lastName: 'lastName30', firstName: 'firstName30', secondName: 'secondName30' } as UserDto,
  { lastName: 'lastName31', firstName: 'firstName31', secondName: 'secondName31' } as UserDto,
  { lastName: 'lastName32', firstName: 'firstName32', secondName: 'secondName32' } as UserDto,
  { lastName: 'lastName33', firstName: 'firstName33', secondName: 'secondName33' } as UserDto,
  { lastName: 'lastName34', firstName: 'firstName34', secondName: 'secondName34' } as UserDto,
  { lastName: 'lastName35', firstName: 'firstName35', secondName: 'secondName35' } as UserDto,
  { lastName: 'lastName36', firstName: 'firstName36', secondName: 'secondName36' } as UserDto,
  { lastName: 'lastName37', firstName: 'firstName37', secondName: 'secondName37' } as UserDto,
  { lastName: 'lastName38', firstName: 'firstName38', secondName: 'secondName38' } as UserDto,
  { lastName: 'lastName39', firstName: 'firstName39', secondName: 'secondName39' } as UserDto,
  { lastName: 'lastName40', firstName: 'firstName40', secondName: 'secondName40' } as UserDto,
  { lastName: 'lastName41', firstName: 'firstName41', secondName: 'secondName41' } as UserDto,
  { lastName: 'lastName42', firstName: 'firstName42', secondName: 'secondName42' } as UserDto
]
